### ISSUE TITLE
Keeps panicking with `entered unreachable code` because of `poll-promise` v0.2.0

### ISSUE THREAD

**Issue by feathecutie** [RainbowCookie32/rusty-psn#172] opened 2023-10-01 14:15 UTC
I can't run rusty-psn without it panicking, and the issue seems to be related to `poll-promise`.
The exact issue is
```
thread 'main' panicked at 'internal error: entered unreachable code', /build/rusty-psn-0.3.0-vendor.tar.gz/poll-promise/src/promise.rs:285:49
```
According to [this issue](https://github.com/EmbarkStudios/poll-promise/issues/19), this seems to be caused by a fatal bug in `poll-promise` version 0.2.0 that is resolved in 0.3.0, which rusty-psn should update to if possible.

**Comment by RainbowCookie32** [comment] 2023-10-01 14:27
Thanks for the report and for tracking down the cause. I'll update all the dependencies in a bit and tag a new release

**Comment by RainbowCookie32** [comment] 2023-10-01 15:01
Pushed 233d80ce878e496bc35c4b1f794e811493071b22 with the updated dependencies. Everything seems to be working on my side, but please test once it's done building: https://github.com/RainbowCookie32/rusty-psn/actions/runs/6371439405

**Comment by RainbowCookie32** [comment] 2023-10-01 18:48
Tagged the [new release](https://github.com/RainbowCookie32/rusty-psn/releases/tag/v0.3.6). I'll close this assuming it's fixed now, but let me know if there's still an issue and I'll reopen.

**Closed by RainbowCookie32** 2023-10-01 18:48 UTC

**Comment by feathecutie** [comment] 2023-10-05 09:23
Works perfectly now, thanks!

Sadly the update to `poll-promise` v0.3.0 comes with its own can of worms when trying to update the [rusty-psn package](https://search.nixos.org/packages?channel=unstable&show=rusty-psn) for the [Nix](https://nixos.org/) package manager because `poll-promise` started using the `document-features` crate which [doesn't work well with vendored dependencies](https://github.com/slint-ui/document-features/issues/20) as Nix uses them, but this is something I'll have to look into further. It definitely doen't seem to be  something that can be fixed on rusty-psn's side.

**Comment by RainbowCookie32** [comment] 2023-10-05 12:28
Sucks that something else broke with the fix.
It's indeed not something I can fix on my side afaik, not without either forking `poll-promise` to nuke the dependency, or replacing `poll-promise` with something else. *Both are a pain.*
I'll try to keep a closer eye on dependency updates at least, in case it gets magically fixed.

**Comment by surfaceflinger** [comment] 2024-04-28 08:25
@RainbowCookie32 document-feature got fixed, opened an issue in poll-promise to tag a new release with bumped deps https://github.com/EmbarkStudios/poll-promise/issues/27
