### ISSUE TITLE
Entered unreachable code on NixOS Linux

### ISSUE THREAD

**Issue by Velkee** [RainbowCookie32/rusty-psn#203] opened 2024-02-28 09:53 UTC
Hi! Experienced a problem running the Linux version of this program on NixOS. The error Rust gave me indicated the program panicked at `/build/rusty-psn-0.3.0-vendor.tar.gz/poll-promise/src/promise.rs:285:49` due to unreachable code. Luckily for me, running the Windows version in Wine worked well :P 

I'm running NixOS which might be causing the issue somehow, but I don't have a computer with a more standard distro anywhere nearby at the moment to test it.

**Comment by RainbowCookie32** [comment] 2024-02-28 14:55
I think this is a duplicate of #172, which was fixed on v0.3.6. The path you posted shows you are running 0.3.0, so update rusty-psn and try again.

**Comment by RainbowCookie32** [comment] 2024-03-04 21:40
Assuming fixed

**Closed by RainbowCookie32** 2024-03-04 21:40 UTC
